services:
  postgres:
    image: postgres:16-alpine
    container_name: philosophers-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - philosophers-net

  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: philosophers-api
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/postgres
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: yourpassword
      SPRING_PROFILES_ACTIVE: dev
      JWT_SECRET: my-secret-key
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      - philosophers-net

networks:
  philosophers-net:
    driver: bridge